"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DB_HOST = exports.PUBLIC_URL = exports.JWT_SECRET = exports.NODE_ENV = exports.DB_USER = exports.DB_TEST_DATABASE = exports.DB_DATABASE = exports.DB_PASSWORD = exports.PORT = void 0;
const dotenv_1 = require("dotenv");
(0, dotenv_1.config)();
exports.PORT = process.env.PORT || 3000;
exports.DB_PASSWORD = process.env.DB_PASSWORD;
exports.DB_DATABASE = process.env.DB_DATABASE;
exports.DB_TEST_DATABASE = process.env.DB_TEST_DATABASE;
exports.DB_USER = process.env.DB_USER;
exports.NODE_ENV = process.env.NODE_ENV;
exports.JWT_SECRET = process.env.JWT_SECRET;
exports.PUBLIC_URL = process.env.MYSQL_URL;
exports.DB_HOST = process.env.DB_HOST;
