"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const CardsController_1 = require("../controllers/CardsController");
const CardsRouter = (0, express_1.Router)();
CardsRouter.get("/Cards", CardsController_1.getAllCardsController);
CardsRouter.get("/Cards/:id", CardsController_1.getCardsByIdController);
CardsRouter.post("/Cards", CardsController_1.saveCardsController);
CardsRouter.delete('/Cards/:id', CardsController_1.deleteCardController);
CardsRouter.put('/cards/:id', CardsController_1.updateCardController);
exports.default = CardsRouter;
